### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by noffle** [noffle/ipget#18]
- [ ] basic feature completeness (focus on pkg manager use cases)
  - [ ] re-expose progress bars and optional verbose output<sup>1</sup>
  - [ ] [custom bootstrap list](https://github.com/noffle/ipget/issues/12)
  - [ ] *what else should be here?*
- [ ] package and get `ipget` on major package managers
  - [ ] [Ubuntu](http://packages.ubuntu.com/)
  - [ ] [Debian](https://www.debian.org/distrib/packages)
  - [ ] [Arch Linux AUR](https://aur.archlinux.org/)
  - [ ] [NixOS](https://nixos.org/nixos/packages.html)
  - [ ] *add yours here!*

<sup>1</sup> super important, since `ipget` can often take several seconds to bootstrap and download.

**Comment by dignifiedquire** [comment]
Homebrew is super easy to do: https://github.com/Homebrew/homebrew/blob/master/CONTRIBUTING.md#add-a-new-formula-for-foo-version-234-from-url

**Comment by whyrusleeping** [comment]
Hey @noffle! I saw you we're around here today, what are the remaining TODO's for getting ipget up and running? 

@Kubuxu was wanting to help out finishing this up, where would the best place for him to start be?

**Comment by noffle** [comment]
Hey! The checklist above is accurate: tackling any of those issues would be of great help.

@Kubuxu  Low hanging fruit might be https://github.com/noffle/fallback-ipfs-shell/issues/2 or ensuring that the example hashes + pubkey are on Sol + always available, so folks can try out the tool by following the README.
